region              = "us-east-1"
ami                 = "ami-090fa75af13c156b4"
instance_type       = "t2.micro"
key_name            = "devopskey"
name                = "Server-test"
env                 = "QA"
owner               = "devops-team"
